# This file defines the content types on the website. See the documentation for
# details: https://docs.bolt.cm/contenttypes/intro

# The Homepage content type is a singleton: There can be only one record of this
# content type.

homepage:
    name: Homepage
    singular_name: Homepage
    fields:
        image:
            type: image
            label: "Image d'entête"
            localize: true
        title:
            type: text
            class: large
            group: content
            localize: true
            label: Titre
            postfix: |
                La 'page d\'accueil' peut contenir des informations de base sur le site Web. Ce titre sera 
                affiché sur la page d'accueil du site. Pour changer le <em><strong>nom</strong></em> du site,
                affiché dans l'en-tête, et dans l'onglet du navigateur Web, modifiez la valeur de <code>sitename:</code> 
                dans le fichier de configuration principal.
        logo:
            type: image
            label: "Logo de l'atelier"
            localize: true
        body:
            type: redactor
            localize: true
            label: Contenu
        sponsors:
            type: collection
            label: Partenaires
            group: Partenaires
            fields:
                sponsor:
                    type: set
                    label: Partenaire
                    fields:
                        title:
                            type: text
                            label: Nom
                            localize: true
                        logo:
                            type: image
                            label: Logo
                            localize: true
                        link:
                            type: text
                            label: lien
                            localize: true
        slug:
            type: slug
            uses: title
            group: Meta
            localize: true
    viewless: false
    taxonomy: [ categories, tags, foobars ]
    locales: fr
    singleton: true
    icon_many: "fa:home"
    icon_one: "fa:home"


# Pages can be used for the more 'static' pages on your site. This content-type
# has a 'templateselect' field, which allows you to override the record_template
# setting for an individual page.
# The taxonomy for this ContentType is defined as 'groups', which is a so-called
# "grouping taxonomy". This way you can easily group sets of pages that logically
# belong together. If your site has a 'services' section, in which you'd like to
# list the different types of services a company provides, you can group these
# together.

pages:
    name: Pages
    singular_name: Page
    title_format: '{title}'
    excerpt_format: '{teaser}'
    fields:
        content:
            type: article
            localize: true
            group: Contenu
            label: |
                Contenu de la page (WISIWIG)        
        title:
            type: text
            class: large
            group: Général
            label: |
                Titre de la page
            localize: true
        image:
            type: image
            label: |
                Image d'entête
            localize: true
            group: Général
        logo:
            type: image
            label: Logo de la page
            postfix: "Ce logo est utilisé par exemple, pour introduire les Pages des trois pôles d'activités (Logo Coworking, Fablab, Formation)."
            localize: true
            group: Général
        slug:
            type: slug
            uses: title
            group: Meta
            localize: true
        template:
            type: templateselect
            filter: '/^[^_].*\.twig$/'
            group: Meta
            localize: true
    listing_records: 6
    default_status: published
    locales: ['fr']
    order: id


# Entries can be used for things like 'news' or 'blogpostings'. They have a
# 'teaser', which can be used for a short blurb on listing-pages, allowing
# visitors to click-through to the rest of the entry. It also has fields for an
# image and an optional video embed.
# A relation is defined to the pages ContentType. This way you can refer to a
# page from your news-item.
# This ContentType defines 'categories' and 'tags' as taxonomies, allowing the
# editor to use both to categorize a specific entry.
# The 'order' is set to '-datepublish', which means that newer entries will be
# shown above older entries.

articles:
    name: Articles
    singular_name: Article
    title_format: '{title}'
    excerpt_format: '{teaser}'
    fields:
        title:
            type: text
            class: large
            group: Entry
            localize: true
        teaser:
            type: textarea
            postfix: |
                A text-only version of the content, that can be used to "tease"
                the content when it's used in listing pages or search results.
            localize: true
        image:
            type: image
            upload: entries
            localize: true
        body:
            type: article
            localize: true
        slug:
            type: slug
            uses: title
            group: Meta
            localize: true
        priority:
            type: select
            values:
                a: |
                    Mettre en avant
                b: |
                    Mettre en second
                c: |
                    Priorité normal
            default: [c]
            group: Meta
            label: |
                Priorité d'affichage
            localize: true

    relations:
        articles:
            multiple: true
            order: title
            label: "Lien avec d'autres Articles"
        people:
            multiple: false
            label: Author of this Entry
            required: false
    taxonomy: [ categories, tags, groups ]
    record_template: article.twig
    listing_template: blog-listing.twig
    listing_records: 10
    default_status: published
    order: -publishedAt
    records_per_page: 10
    icon_many: "fa:file-alt"
    icon_one: "fa:file-alt"
    locales: ['fr']


# The 'People' ContentType can be used to build pages about the people in your
# company, organisation or any other kind of team.

people:
    name: People
    singular_name: Person
    title_format: "{name} ({description})"
    fields:
        name:
            type: text
            class: large
            variant: inline
            fixture_format: '{name}'
            localize: true
        description:
            type: text
            variant: inline
            postfix: This person's job description, title or somesuch
            fixture_format: '{jobTitle}'
            localize: true
        email:
            type: text
            variant: inline
            fixture_format: '{safeEmail}'
            localize: true
        image:
            type: image
            localize: true
        content:
            type: redactor
            localize: true
        contentlink:
            type: text
            label: Link
            placeholder: 'contentType/slug or https://example.org/'
            postfix: "Use this to add a link for this Person. This could either be an 'internal' link like <tt>page//about</tt>, if you use a contentType/slug combination. Otherwise use a proper URL, like `https://example.org`. If left blank, it'll default to the internal link to this Record's detail page."
            fixture_format: '{url}'
            localize: true
        slug:
            type: slug
            uses: [ name ]
            localize: true
    taxonomy: groups
    icon_one: fa:user
    icon_many: fa:users
    record_template: people.twig
    listing_template: listing.twig
    locales: ['fr']

# The 'People' ContentType can be used to build pages about the people in your
# company, organisation or any other kind of team.

formation:
    name: Formations
    singular_name: Formation
    title_format: "{title}"
    fields:
        title:
            type: text
            class: large
            variant: inline
            fixture_format: '{title}'
            localize: true
        image:
            type: image
            localize: true
        content:
            type: article
            localize: true
        slug:
            type: slug
            uses: [ title ]
            localize: true
        price:
            type: text
            fixture_format: "€ {randomDigitNotNull}0,-"
            localize: true
            relations:
    relations:
        people:
            multiple: true
            label: Formateurs
            required: false
    icon_one: fa:award
    icon_many: fa:award
    record_template: record.twig
    listing_template: listing.twig
    locales: ['fr']

# The 'Products' ContentType can be used to manage information about the
# products or services you (or your company, organisation) provide.

machines:
    name: Machines
    singular_name: Machine
    fields:
        title:
            type: text
            class: large
            variant: inline
            label: Name of this product
            group: Block
            fixture_format: '{catchPhrase}'
            localize: true
        price:
            type: text
            fixture_format: "€ {randomDigitNotNull}0,-"
            localize: true
        image:
            type: image
            localize: true
        teaser:
            type: redactor
            fixture_format: '{paragraph}'
            localize: true
        content:
            type: article
            localize: true
        features:
            type: collection
            label: Caractéristiques
            group: Caractéristiques
            fields:
                feature:
                    type: set
                    label: Caractéristique
                    fields: 
                        title: 
                            type: text
                            label: Titre
                            localize: true
                        value:
                            type: text
                            label: Valeur
                            localize: true
        slug:
            type: slug
            uses: [ title ]
            group: Meta
            localize: true
    show_on_dashboard: true
    viewless: false
    default_status: published
    searchable: false
    order: title
    icon_many: "fa:cogs"
    icon_one: "fa:cog"
    record_template: machine.twig
    listing_template: listing.twig
    locales: ['fr']

# The 'Blocks' ContentType is a so-called 'resource ContentType'. This means
# that it can be used to manage smaller pieces of content, like the 'about us'
# text, an 'our address' in the footer, or similar short blurbs of text.
# For more info, see: https://docs.bolt.cm/howto/resource-contenttype

blocks:
    name: Blocks
    singular_name: Block
    excerpt_format: '{teaser}'
    fields:
        title:
            type: text
            class: large
            label: Title of this Block
            group: Block
            localize: true
        image:
            type: image
            localize: true
        teaser:
            type: redactor
            fixture_format: '{paragraph}'
            localize: true
        content:
            type: redactor
            localize: true
        contentlink:
            type: text
            label: Link
            placeholder: 'contentType/slug or https://example.org/'
            postfix: "Use this to add a link for this Homepage. This could either be an 'internal' link like <tt>page//about</tt>, if you use a contentType/slug combination. Otherwise use a proper URL, like `https://example.org`."
            fixture_format: '{url}'
            localize: true
        slug:
            type: slug
            uses: [ title ]
            group: Meta
            localize: true
    show_on_dashboard: true
    viewless: true
    default_status: published
    searchable: false
    order: title
    icon_many: "fa:cubes"
    icon_one: "fa:cube"
    locales: ['fr']

# Possible field types:
#
# text - varchar(256) - input type text.
# number - double - Input field for numbers, with `mode: integer` or `mode: float`
# imagelist - text (65kb) - Input type for imagelists. Add multiple images. Useful for image sliders, galleries, etcetera.
# image - varchar(256) - image select/upload widget, stored as filename.
# file - varchar(256) - file select/upload widget, stored as filename.
# filelist - text (65kb) - Input type for a list of files. Including a description.
# embed - text (65kb) - embed widget for video and audio. Stored as JSON.
# html - text (65kb) - wysiwyg element.
# textarea - varchar(32768) - Simple, plain < textarea > field.
# markdown - varchar(32768) - wysiwyg element, which is parsed as Markdown text.
# date - datetime - date selector widget, with `mode: date` or `mode: datetime`
# email - text(65kb) - Input type for email.
# select - varchar(256) - select with predefined values
# templateselect - varchar(256) - select with template filenames
# checkbox - integer - checkbox-field which is 1 (checked) or 0 (unchecked)
# set - text (65kb) - Input type for sests. Group fields semantically into a combined set field.
# collection - text (65kb) - Input type for collections. Add multiple fields of different types. Useful for lists.
# data - text (65kb) - Read-only field, useful for storing (raw) data provided by an external source.
# hidden - text (65kb) - Regular text field, except it is hidden from the content editor.
# slug - text(65kb) - The slug for the record. Use with option `uses: [ title ]` to generate based on a title field.

# Using YAML repeated nodes
#
# YAML allows the defining of "repeated nodes". These allow you to define a 'node'
# with a 'key: &name' and referenced later with '<<: *name'
#
# Bolt allows you to define this with the special entry of '__nodes:' that itself
# won't create a ContentType, but will allow you to use it in actual ContentTypes
# to prevent repeating yourself.
#
# To achieve this, first create a key '__nodes:' and place it before your other contenttypes:
#__nodes:
#    field_defaults: &field_defaults
#        title:
#            type: text
#            class: large
#            group: main
#        slug:
#            type: slug
#            uses: title
#    template_defaults: &template_defaults
#        template:
#            type: templateselect
#            filter: '*.twig'
#            group: meta
#
# Then, as an example, you could create a ContentType with default fields, with
# an additional 'image' field.
#
#contenttypeabc:
#    name: ContentType Abc
#    slug: contenttypeabc
#    fields:
#        <<: *field_defaults
#        image:
#            type: image
#            attrib: title
#            extensions: [ gif, jpg, png ]
#        <<: *template_defaults
#    taxonomy: [ chapters ]
#    records_per_page: 10
#
# Alternatively, or additionally, you then can then create a ContentType with
# default fields, and a 'select' field, and a different 'templateselect' option.
#
#contenttypexyz:
#    name: ContentType Xyz
#    slug: contenttypexyz
#    fields:
#        <<: *field_defaults
#        selectfield:
#            type: select
#            values: [ none, foo, bar ]
#        template:
#            type: templateselect
#            filter: '*_xyz.twig'
#    taxonomy: [ tags ]
#    records_per_page: 20
