# This file defines the different types of taxonomies in Bolt. See the
# documentation for details: https://docs.bolt.cm/contenttypes/taxonomies

tags:
    slug: tags
    singular_slug: tag
    behaves_like: tags
    postfix: "Add some freeform tags. Start a new tag by typing a comma or space."
    allow_spaces: false
    listing_template: blog-listing.twig #custom template
    required: false

categories:
    name: Categories
    slug: categories
    singular_name: Category
    singular_slug: category
    behaves_like: categories
    multiple: true
    options: [ actu, événement, film, musique, livre, amour, fun, projet, tutoriel]
    required: false
    listing_template: blog-listing.twig #custom template

groups:
    name: Groups
    slug: groups
    singular_name: Group
    singular_slug: group
    behaves_like: groups
    multiple: true
    options: [ Irreductibles, Coworkers, Makers, Formateurs]
    required: false